In [2]:
import pandas as pd
import numpy as np

In [41]:
df_train = pd.read_csv('train.csv')
df_train.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
df_test = pd.read_csv('test.csv')
df_test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
#df.astype('int', inplace=True)
#df.sum()

In [36]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [71]:
y_train = df_train.iloc[:,0]
X_train = df_train.iloc[:, 1:]
X_test = df_test.iloc[:, :]
y_label = np.array([])

In [ ]:
for i,C in enumerate((100,1,0.01)):
    clf_l1_LR = LogisticRegression(C=C, penalty='l1', tol=0.01)
    #clf_l2_LR = LogisticRegression(C=C, penalty='l2', tol=0.01)
    clf_l1_LR.fit(X_train,y_train)
    #clf_l2_LR.fit(X,y)
    y_test_1 = clf_l1_LR.predict(X_test)
    #y_test_1 = list(y_test_1)
    #y_test.append(y_test_1)
    #print (type(y_test_1))
    filename = 'sample_submission_' + 'l1_' + str(C) + '.csv'
    with open(filename, 'a') as the_file:
        the_file.write('ImageId' + ' '+'Label' + '\n')
        for i, item in enumerate(y_test_1):
            the_file.write(str(i) + ' '+str(item) + '\n')       
    #print (y_test_1)
#y_test